# Generated by Django 5.1.2 on 2024-11-19 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_employeeavailability_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Numero de telefono'),
        ),
        migrations.AlterField(
            model_name='employeeavailability',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Disponibilidad Empleado +', to='users.employee'),
        ),
    ]
