# Generated by Django 5.1.2 on 2024-11-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Correo Cliente')),
                ('customer_name', models.CharField(max_length=64)),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
            ],
            options={
                'verbose_name': 'Formulario de Contacto',
                'verbose_name_plural': 'Formularios de Contacto',
            },
        ),
    ]
