# Generated by Django 5.1.2 on 2024-11-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to='', verbose_name='Imagen')),
                ('title', models.CharField(max_length=30, verbose_name='Titulo')),
                ('content', models.CharField(max_length=300, verbose_name='Contenido')),
                ('active', models.BooleanField(default=False, verbose_name='Activo')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articulos',
            },
        ),
    ]
