# Generated by Django 5.1.2 on 2024-11-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
    ]
