# Generated by Django 5.1.2 on 2024-11-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_employee_alter_booking_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('finalized', 'Finalizado')], default='pending', max_length=30, verbose_name='Estado'),
        ),
    ]
