# Generated by Django 5.1.2 on 2024-11-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='confirmed',
        ),
        migrations.AlterField(
            model_name='booking',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
