# Generated by Django 5.1.2 on 2024-11-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_remove_booking_confirmed_alter_booking_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('finalized', 'Finalizado'), ('cancelled', 'Cancelado')], default='pending', max_length=30, verbose_name='Estado'),
        ),
    ]
